### ISSUE TITLE
Jupyterlab shows tables in black on black

### ISSUE THREAD

**Issue by horsto** [datajoint/datajoint-python#1167]
In Jupyterlab table previews are suddenly unreadable in dark and dark-high-contrast themes. I am not sure what happened here, but I seem not to be able to revert it to showing the font in white. This might be a jupyter lab issue and not a datajoint issue. 

OS: Mac OS
Jupyter lab: Version 4.2.4
Datajoint python: Version 0.14.1

<img width="405" alt="Screenshot 2024-08-14 at 11 38 45" src="https://github.com/user-attachments/assets/eeb5ca34-d2ea-43dd-9de0-b2a6129f2787">

**Comment by CBroz1** [comment]
The html table style is defined [here](https://github.com/datajoint/datajoint-python/blob/master/datajoint/preview.py#L58), hardcoded for light themes. Running an editable install will allow you to adjust these values

**Comment by dimitri-yatsenko** [comment]
@CBroz1 what would you suggest for a better solution?

**Comment by CBroz1** [comment]
I can see a few possible paths...

1. Determine theme and adjust html accordingly. [Discussion](https://github.com/jupyterlab/jupyterlab/issues/3855) 
  - Pros: maintains status quo for light-mode users
  - Cons: maintenance burden of front-end variance
2. Defer rendering to pandas html, which already adjusts for theme.
  - Pros: offloads maintenance to another package, no additional dependencies
  - Cons: 
    - mismatch across versions
    - may require deprecation timeline for html in case someone uses this for other tools
    - minor edits to show primary keys and table header
3. Add a config option that determines the html displayed
  - Pros: maintains status quo, no interface changes, minimal work
  - Cons: Additional config line item

<details><summary>Example Pandas adjustment for primary keys</summary>

```python
import pandas as pd
from IPython.display import display

data = {
    'id': [1, 2, 3],
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [24, 27, 22],
    'email': ['alice@example.com', 'bob@example.com', 'charlie@example.com']
}
df = pd.DataFrame(data)
primary_key_cols = ['id', 'name']

def style_primary_keys(df, primary_key_cols):
    styled_cols = {col: f"*{col}" if col in primary_key_cols else col for col in df.columns}
    df = df.rename(columns=styled_cols)
    return df

styled_df = style_primary_keys(df, primary_key_cols)
display(styled_df.style)
```
</details>

I don't think 1 isn't worth the additional maintenance burden. 2 may be the most long-term solution, but 3 is an easier short-term solution. I lean toward 2.

**Comment by horsto** [comment]
Has anybody worked on that? 

Screenshot (dj vers 0.14.3)
<img width="552" alt="Image" src="https://github.com/user-attachments/assets/c69f7a0d-7292-474e-b62a-ff0ef9513b03" />

**Comment by CBroz1** [comment]
> Has anybody worked on that?

Not that I'm aware of. I still edit the HTML of my installs for each env

**Comment by horsto** [comment]
Thanks @CBroz1 - could you provide a mini-tutorial here on how to do that?

**Comment by CBroz1** [comment]
> Thanks [@CBroz1](https://github.com/CBroz1) - could you provide a mini-tutorial here on how to do that?

Sure - 

1. Clone this repo, do an editable install within your conda environment

```bash
cd /your/path/for/local/files
git clone https://github.com/datajoint/datajoint-python/
cd ./datajoint-python
conda activate your_env
pip install -e .
```

2. Edit the preview file to change the hex codes (e.g., `#A0A0A0`) of the `css` variable within `repr_html` [here](https://github.com/datajoint/datajoint-python/blob/eef7e59316a05349dc662f34928403808d93e49c/datajoint/preview.py#L57), save the result in `/you/path/for/local/files/datajoint-python/datajoint/preview.py`

<details><summary>My `css` variable</summary>

See variables at the top. Picking colors may be easier with a [color picker](https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color) VSCode extension

```css
    <style type="text/css">
        :root { /* Variables: */
            --my-background-dark: #282a36;
            --my-background-light: #44475a;
            --my-foreground: #f8f8f2;
            --my-lines: #6272a4;
            --my-highlight: #bd93f9;
        }
        .Table{
            border-collapse:collapse;
            background-color: var(--my-background-dark);
            color: var(--my-background-light);
        }
        .Table th{ /* Table Header */
            background: var(--my-background-dark);
            color: var(--my-background-dark);
            padding: 4px;
            border: var(--my-lines) 1px solid;
            text-align: center;
        }
        .Table td{ /* Table Data */
            padding:4px;
            border:var(--my-lines) 1px solid; font-size:100%;
        }
        .Table tr:nth-child(odd){ /* Table Row, Odd */
            background: var(--my-background-light);
            color: var(--my-foreground);
        }
        .Table tr:nth-child(even){ /* Table Row, Even */
            color: var(--my-foreground);
            background: var(--my-background-dark);
        }
        /* Tooltip container */
        .djtooltip {
        }
        /* Tooltip text */
        .djtooltip .djtooltiptext {
            visibility: hidden;
            width: 120px;
            background-color: var(--my-background-light);
            color: var(--my-foreground);
            text-align: center;
            padding: 5px 0;
            border: 1px solid var(--my-lines);
            border-radius: 6px;
            /* Position the tooltip text - see examples below! */
            position: absolute;
            z-index: 1;
        }
        #primary {
            font-weight: bold;
            color: var(--my-highlight);
        }
        #nonprimary {
            font-weight: normal;
            color: var(--my-foreground);
        }

        /* Show the tooltip text when you mouse over the tooltip container */
        .djtooltip:hover .djtooltiptext {
            visibility: visible;
        }
    </style>
```

Based on [dracula theme](https://github.com/dracula/dracula-theme), using [this color scheme](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula)

![Image](https://github.com/user-attachments/assets/fb628c3d-e6b9-4a65-9a75-f211f8194ed1)

</details>

3. Restart the kernel of your jupyter instance to see the effects
